env:
  es6: true
  node: true
parser: babel-eslint
extends: 
  - 'eslint:recommended'
  - 'plugin:react/recommended'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
  ecmaFeatures: 
    jsx: true
rules:
  indent:
    - error
    - 4
  semi:
    - error
    - never
  no-use-before-define:
    - error
  react/prop-types: false
  react/jsx-key: false
  arrow-spacing:
    - 1
    - before: true
      after: true
  no-console:
    - error
    - { allow: ["error"] }
  object-curly-spacing:
    - warn
    - always
  key-spacing:
    - warn
    - afterColon: true

