env:
  es6: true
  node: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  indent:
    - error
    - 4
  semi:
    - error
    - never
  no-use-before-define:
    - error
  no-console: off
    
