swagger: "2.0"
info:
  description: "blog-server interfaces"
  version: "1.0.1"
  title: "Blog-Server"
  host: "localhost:3000"
tags:
  - name: "User"
    description: "User CRUD"
  - name: "Judge"
    description: "评论用户或文章,控制器属于Article"
paths:
  /login:
    post:
      tags:
        - "User"
      summary: "登录"
      description: "登录并获取token,token时效为1day"
      operationId: "login"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "account"
          type: string
          required: true
        - in: "body"
          name: "password"
          type: string
          required: true
  