swagger: "2.0"
info:
  description: "blog-server interfaces"
  version: "1.0.1"
  title: "Blog-Server"
  host: "localhost:3000"
tags:
  - name: "User"
    description: "User CRUD"
  - name: "Judge"
    description: "评论用户或文章,控制器属于Article"
paths:
  /article/judge:
      post:
        tags:
          - "Judge"
        summary: "评论文章"
        operationId: "JudgeArticle"
        parameters:
          - in: "body"
            name: "infos"
            schema:
              type: object
              required:
                - content
                - article
                - author
                - other
              properties:
                content:
                  type: string
                article:
                  type: string
                author:
                  type: string
                other:
                  type: string
  /login:
    post:
      tags:
        - "User"
      summary: "登录"
      description: "登录并获取token,token时效为1day"
      operationId: "login"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: user
          schema:
            type: object
            required: 
              - account
              - password
            properties:
              account:
                type: string
              password:
                type: string
      responses:
        200:
          description: "Success"
    